export interface AppProduct {
    key?: string,
    titleEn: string,
    titleMm: string,
    titleJa: string,
    descriptionEn: string,
    descriptionMm: string,
    descriptionJa: string,
    price?: number,
    category: string,
    dataUrl?: string,
    downloadUrl?: string,
    note?: string,
    createdDate?: Date,
    updatedDate?: Date,
    createdUser?: string,
    updatedUser?: string,
}